title: welcome to coelien's homepage
theme: minima
author: coelien
email: daoxiang@mail.dlut.edu.cn
description: > # this means to ignore newlines until "baseurl:"
 algs blog

# social links
twitter_username: coelien
github_username:  coelien

show_excerpts: true # set to false to remove excerpts on the homepage
